version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: local_database
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: